id: P000430
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN4777
  title: ཕ་དམ་པ་སངས་རྒྱས་དང་མ་ཅིག་ལབ་སྒྲོན་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    47dc8fbade894d7794301e3b76540768:
      image_group_id: I3CN4779
      title: Volume 1 of pha dam pa dang ma cig lab sgron gyi rnam thar/
      volume_number: 1
      total_pages: 660
      base_file: v001.txt
